################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: DigitalDisbursements
  productionDescription: Technology and consumer demands have accelerated digital payment adoption. With extensive and exclusive payout options, plus built-in security, Digital Disbursements makes it easy to deliver fast and efficient digital payouts to customers how and when they want to get paid - on weekends, holidays and after hours across the U.S. and Europe. Leverage our relationships, scale and expertise to quickly, securely and cost-effectively payout customers when and how they want, globally.
  whoIsItFor: Insurance companies, gig economy, market places, lenders, pawn shops, and more.
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: DigitalDisbursements™
getStarted: "/docs/getting-started.md"
featuredFeatures:
  - title: Visa+ 
    description:  The Visa Plus feature enables clients to activate Visa+ as a payout method on the Digital Disbursement Platform (DDP) for Direct Disbursement merchants. The Visa+ Service introduces a new consumer-defined payment-specific "payname" that can be used to identify the payment recipient instead of using sensitive personal data.
    relatedDocs:
      - relatedDoc: 
        title: Visa Plus
        description: Learn how to integrate with our Visa+ capabilities.
        link: docs/documentation/features/visaplus.md
    relatedAPIs:
      - relatedAPI: 
        title: Create and Pay
        description: Create and send a payment with this single API endpoint.
        type: post        
        path: /ddp/v1/payments&version=1.0.0
  - title: Real Time Payments
    description:  Digital Disbursements uses the Real-Time Payments (RTP) network to send payments in as little as 5 seconds. This feature allows developers to utilize a single API to implement real-time fund transfers via ACH rails.
    relatedDocs:
      - relatedDoc: 
        title: FAQs #TODO: Update the link
        description: Take a look at our FAQs. #TODO: Update the link
        link: docs/faq/faq.md #TODO: Update the link
    relatedAPIs:
      - relatedAPI: 
        title: Disburse a Payment
        description: Use this API to send payments in as little as 5 seconds!
        type: patch       
        path: /ddp/v1/payments/{id}/disburse&version=1.0.0
  - title: Peer to Peer Payments
    description:  Peer-to-Peer (P2P) payments refer to transactions where a company facilitates payments between two individuals—a sender and a receiver. This feature allows developers to utilize a single API to implement direct fund transfers between to recipients.
    relatedDocs:
      - relatedDoc: 
        title: Peer-to-Peer (P2P) Payments
        description: Learn how to integrate with our P2P payment capabilities.
        link: docs/documentation/features/p2p.md
    relatedAPIs:
      - relatedAPI: 
        title: Disburse a Payment
        description: Use this API to send payments in as little as 5 seconds!
        type: patch       
        path: /ddp/v1/payments/{id}/disburse&version=1.0.0
